### ISSUE TITLE
@rjsf/core/utils deprecated in rjsf v.5

### ISSUE THREAD

**Issue by Zonxpk** [ivarprudnikov/rjsf-conditionals#452]
**Describe the bug**

<img width="411" alt="image" src="https://user-images.githubusercontent.com/50532697/203305547-7baf517b-8855-4c6a-89cb-cadc9641cc84.png">

rjsf-conditionals cannot use with rjsf v.5 because they moved to @rjsf/utils [](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/utility-functions/)

**To Reproduce:**
  - Make a fallback try catch between v.4 and v.5

`const rjsfCore = require("@rjsf/core");
let deepEquals;

try{
  deepEquals = rjsfCore.utils.deepEquals;
} catch(error) {
  const utils = require("@rjsf/utils");
  deepEquals = utils.deepEquals;
}
`

**Library details:**
  - @rjsf/core: ^5.0.0-beta.13
  - @rjsf/utils: ^5.0.0-beta.13
  - rjsf-conditionals: ^1.4.0

**Comment by ba11en** [comment]
i ran into this issue as well, would love to use rjsf v5 with rjsf-conditionals, thanks for your work on this repo @ivarprudnikov

**Comment by ivarprudnikov** [comment]
Should be fixed in https://www.npmjs.com/package/rjsf-conditionals/v/1.5.0 now. 
Reimplemented the same equals method as in rjsf v5 beta instead of pulling all of the new utils package. The comparison implementation is different to the ones in v2 v3 and v4 and uses `lodash.isEqualsWith` now, which might cause issues for older versions. But the tests passed so 🤷‍♂️ It is just not clear if this is a breaking change TBH

**Comment by ba11en** [comment]
legend! thank you, ill give it a run this week 🙌
