### ISSUE TITLE
question: is there a way to use conditions on properties nested in array items?

### ISSUE THREAD

**Issue by ba11en** [ivarprudnikov/rjsf-conditionals#504]
i cant see any way of getting at properties that are added to array items in order to add conditions for these, as they have an index in the idSchema to access them.  

ive tried this:
`{   
    "conditions": {
      "itemList.items[0].name": {
        "is": "empty"
      }
    },
    "event": [
      {
        "type": "remove",
        "params": {
          "field": ["itemList.items[0].age"]
        }
      }
    ]
  }`

and this `itemList[0].name` 

etc

which throws an error.  

rjsf playground here for schema example:
[https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpdGVtc0xpc3QiOlt7InRoaW5nIjp7ImFnZSI6MTIzLCJuYW1lIjoidGVzdCJ9fV19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiaXRlbXNMaXN0Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRoaW5nIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIifX19fX19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJleHBlcmltZW50YWxfZGVmYXVsdEZvcm1TdGF0ZUJlaGF2aW9yIjp7ImFycmF5TWluSXRlbXMiOnsicG9wdWxhdGUiOiJwb3B1bGF0ZSIsIm1lcmdlRXh0cmFEZWZhdWx0cyI6ZmFsc2V9LCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19](url)

not sure how to proceed or whether it is even possible without forking the code, even then im not sure, thought id ask first.. 
if you have any thoughts please let me know, thanks for your help @ivarprudnikov

**Comment by ba11en** [comment]
thought i might be able to reference a definition in the schema, but no luck there

**Comment by ivarprudnikov** [comment]
I see that array field selector throws a validation error because of the square bracket. There is also no test for that but I think it should be possible to fix it as `json-rules-engine-simplified` mentions in the docs that it should support anything `selectn` supports and that in turn supports array element selection.

**Comment by ivarprudnikov** [comment]
But if you look into the readme then it seems that specific array entries are not supported per se https://github.com/RXNT/json-rules-engine-simplified/tree/948d16247e67aab907acc69bdd5aff3256bbe3b5#nested-arrays-object-queries

**Comment by ivarprudnikov** [comment]
To sum up I think it is possible in theory by extending the rules engine with some custom events and/or extra actions. On the other hand I would question if having specific conditionals for each item in an array even makes sense. A specific real world example could help understand if such a form should exist or if there is a better way to represent it in a schema.

I'll close this because the reported issue relates to the capabilities of the rules engine rather than this library.

**Comment by ba11en** [comment]
thanks @ivarprudnikov  for the responses, ill look into selectn as you have mentioned and see what i can come up with. I wasnt intending on having different conditions for each item in an array, just a rule that applies to all items in the array, but obviously only affects each item individually as the selections change. 
eg a simple remove action on a boolean checkbox that adds or removes a textfield, per item in the array

**Comment by ba11en** [comment]
ok ive had a play around and it seems impossible to do what i need
Its only possible to remove _every_ instance of a property in the array if _any_ of the dependant properties in the array are true. 

As the schema doesnt actually update and populate with the dynamic array items that have been added to the form, the rules action has no way of removing a field of a specific element of the array - cause it doesnt actually exist in the schema.

if you have any ideas please let me know, thanks again..

guess i could use oneOf or if-then-else for individual array items
